#!/bin/bash

# Node details:
TYPE=iol
CONTROLLER=172.17.0.1
LABEL=0
ID=1
ARGS="-g ${CONTROLLER} -i ${ID} -l ${LABEL} -f /opt/image/iol.bin -t -w R0 -- -q -n 4096 -e 1 -s 1"

HOSTNAME=$(cat /opt/image/iourc | grep "=" | head -n1 | sed 's/\ *=.*//')
export HOSTNAME

function die {
	echo $1
	exit 1
}

# Building the management switch
brctl addbr mgmt0 &> /dev/null || die "ERROR: failed to add mgmt0 bridge"
ip addr add 192.0.2.1/24 dev mgmt0 &> /dev/null || die "ERROR: failed to set IP address of mgmt0 bridge"
ip link set mgmt0 up &> /dev/null || die "ERROR: failed to bring mgmt0 bridge up"
tunctl -u root -g root -t veth0 &> /dev/null || die "ERROR: failed to create veth0 interface"
ip link set dev veth0 up &> /dev/null || die "ERROR: failed to bring veth0 interface up"
brctl addif mgmt0 veth0 &> /dev/null || die "ERROR: failed to attach veth0 to mgmt0 bridge"
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &> /dev/null || die "ERROR: failed to configure iptables (MASQUERADE on eth0)"
iptables -t nat -A POSTROUTING -o mgmt0 -j MASQUERADE &> /dev/null || die "ERROR: failed to configure iptables (MASQUERADE on mgmt0)"
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8022 -j DNAT --to 192.0.2.254:22 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 22 on eth0)"
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8023 -j DNAT --to 192.0.2.254:23 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 23 on eth0)"
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8080 -j DNAT --to 192.0.2.254:80 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 80 on eth0)"
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8443 -j DNAT --to 192.0.2.254:443 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 443 on eth0)"
iptables -t nat -A PREROUTING -i mgmt0 -p udp --dport 69 -j DNAT --to ${CONTROLLER}:69 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 69 on mgmt0)"
iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 20 -j DNAT --to ${CONTROLLER}:20 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 20 on mgmt0)"
iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 21 -j DNAT --to 172.17.0.1:21 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 21 on mgmt0)"
iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 22 -j DNAT --to 172.17.0.1:22 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 22 on mgmt0)"
iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 80 -j DNAT --to 172.17.0.1:80 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 80 on mgmt0)"
iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 443 -j DNAT --to 172.17.0.1:443 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 443 on mgmt0)"

mv /opt/image/nvram_00000 /opt/image/nvram_$(printf "%05d" ${ID}) &> /dev/null || die "ERROR: failed to fix NVRAM"
echo -e "127.0.0.1 localhost\n127.0.1.1 ${HOSTNAME}\n127.0.0.127 xml.cisco.com" > /etc/hosts 2> /dev/null || die "ERROR: failed to set /etc/hosts"
echo "${HOSTNAME}" > /etc/hostname 2> /dev/null && hostname ${HOSTNAME} &> /dev/null || die "ERROR: failed to set hostname"
mkdir -p /tmp/netio0 &> /dev/null || die "ERROR: failed to create directory (/tmp/netio)"
curl -m 3 -s http://${CONTROLLER}/api/wrappers/wrapper_${TYPE}.py > /sbin/wrapper.py 2> /dev/null || die "ERROR: cannot download wrapper"
curl -m 3 -s http://${CONTROLLER}/api/wrappers/wrapper_modules.py > /usr/lib/python3.4/wrapper_modules.py 2> /dev/null || die "ERROR: cannot download wrapper modules"
chmod 755 /sbin/wrapper.py || die "ERROR: cannot make wrapper executable"

echo "INFO: starting wrapper: /sbin/wrapper.py ${ARGS}"
/sbin/wrapper.py ${ARGS}
