#!/usr/bin/env ansible-playbook
---
- hosts: switches
  gather_facts: False
  connection: network_cli
  tasks:
    - name: CONFIGURE VLANS
      ios_vlan:
        vlan_id: "{{item.vlan_id}}"
        name: "{{item.name}}"
        state: present
      with_items:
        - {vlan_id: "2", name: "R1-R2"}
        - {vlan_id: "3", name: "R2-R3"}
    - name: CONFIGURE ACCESS INTERFACES (SW1)
      ios_vlan:
        vlan_id: 2
        interfaces:
          - Ethernet0/1
      when: inventory_hostname == "sw1"
    - name: SETTING ENCAPSULATION (SW1)
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: "interface {{item}}"
      with_items:
        - Ethernet0/0
        - Ethernet0/2
    - name: CONFIGURE TRUNK INTERFACES (SW1)
      ios_l2_interface:
        name: "{{item}}"
        mode: trunk
        native_vlan: 1
        trunk_allowed_vlans: 1-3
      with_items:
        - Ethernet0/0
        - Ethernet0/2
      when: inventory_hostname == "sw1"
    - name: CONFIGURE ACCESS INTERFACES (SW2)
      ios_vlan:
        vlan_id: 3
        interfaces:
          - Ethernet0/1
      when: inventory_hostname == "sw2"
    - name: SETTING ENCAPSULATION (SW1)
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: interface Ethernet0/0
    - name: CONFIGURE TRUNK INTERFACES (SW2)
      ios_l2_interface:
        name: "{{item}}"
        mode: trunk
        native_vlan: 1
        trunk_allowed_vlans: 1-3
      with_items:
        - Ethernet0/0
      when: inventory_hostname == "sw2"

