---
- name: "INSTALLING PYTHON SETUPTOOLS MODULE"
  pip:
    executable: pip3
    name:
      - setuptools

- name: "INSTALLING PYTHON MODULES"
  pip:
    executable: pip3
    name:
      - fbtftp
      - lxml
      - pexpect
      - salt
      - selenium
      - zeep
      - ansible==2.7.0
      - nornir==1.1.0


- file:
    src: /usr/lib/chromium-browser/chromedriver
    dest: /usr/local/bin/chromedriver
    state: link

- file:
    path: "{{item.path}}"
    state: directory
    mode: 0755
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items:
    - {path: "/opt/customtftp/tftproot", owner: "root", group: "root"}
    - {path: "/root/scripts", owner: "root", group: "root"}
    - {path: "/opt/unetlab/labs/Courses/NetDevOps", owner: "www-data", group: "www-data"}
    - {path: "/etc/salt/pillar", owner: "root", group: "root"}
    - {path: "/usr/src/axlsqltoolkit", owner: "root", group: "root"}

- copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "salt_master", dest: "/etc/salt/master", owner: "root", group: "root", mode: "0644"}
    - {src: "salt_minion", dest: "/etc/salt/minion", owner: "root", group: "root", mode: "0644"}
    - {src: "salt_proxy", dest: "/etc/salt/proxy", owner: "root", group: "root", mode: "0644"}

- name: "UPLOADING LABS"
  copy:
    src: "labs/Courses/{{item}}"
    dest: "/opt/unetlab/labs/Courses/{{item}}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - NetDevOps/ZTP.unl
    - NetDevOps/ScreenScraping.unl
    - NetDevOps/Ansible.unl
    - NetDevOps/SaltStack.unl
    - NetDevOps/NetRestConf.unl
    - NetDevOps/NativeAPI.unl

- name: "UPLOADING FILES"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: "{{item.mode}}"
  with_items:
    - {src: "custom_tftp.py", dest: "/usr/local/sbin/custom_tftp.py", mode: "0755"}
    - {src: "dhcpd.conf", dest: "/etc/dhcp/dhcpd.conf", mode: "0644"}
    - {src: "poap.py", dest: "/opt/customtftp/tftproot/poap.py", mode: "0644"}
    - {src: "files/Cisco/Nexus/nxos.7.0.3.I7.1.bin",  dest: "/opt/unetlab/html/files/nxos.7.0.3.I7.1.bin", mode: "0644"}
    - {src: "files/Cisco/Nexus/nxos.7.0.3.I7.1.bin.md5",  dest: "/opt/unetlab/html/files/nxos.7.0.3.I7.1.bin.md5", mode: "0644"}
    - {src: "webscraping_lab1.py",  dest: "/root/scripts/webscraping_lab1.py", mode: "0755"}
    - {src: "pexpect_lab1.py",  dest: "/root/scripts/pexpect_lab1.py", mode: "0755"}
    - {src: "pexpect_lab2.py",  dest: "/root/scripts/pexpect_lab2.py", mode: "0755"}
    - {src: "netmiko_lab1.py",  dest: "/root/scripts/netmiko_lab1.py", mode: "0755"}
    - {src: "netmiko_lab2.py",  dest: "/root/scripts/netmiko_lab2.py", mode: "0755"}
    - {src: "napalm_lab1.py",  dest: "/root/scripts/napalm_lab1.py", mode: "0755"}
    - {src: "napalm_lab2.py",  dest: "/root/scripts/napalm_lab2.py", mode: "0755"}
    - {src: "napalm_lab3.py",  dest: "/root/scripts/napalm_lab3.py", mode: "0755"}
    - {src: "hosts.yaml",  dest: "/root/scripts/hosts.yaml", mode: "0644"}
    - {src: "groups.yaml",  dest: "/root/scripts/groups.yaml", mode: "0644"}
    - {src: "nornir_lab1.py",  dest: "/root/scripts/nornir_lab1.py", mode: "0755"}
    - {src: "nornir_lab2.py",  dest: "/root/scripts/nornir_lab2.py", mode: "0755"}
    - {src: "ansible.cfg",  dest: "/root/scripts/ansible.cfg", mode: "0755"}
    - {src: "ansible-hosts",  dest: "/root/scripts/ansible-hosts", mode: "0755"}
    - {src: "ansible_lab_3_1.yaml",  dest: "/root/scripts/ansible_lab_3_1.yaml", mode: "0755"}
    - {src: "ansible_lab_3_2.yaml",  dest: "/root/scripts/ansible_lab_3_2.yaml", mode: "0755"}
    - {src: "devices.csv",  dest: "/root/scripts/devices.csv", mode: "0644"}
    - {src: "jinja2_lab1.py",  dest: "/root/scripts/jinja2_lab1.py", mode: "0755"}
    - {src: "jinja2_lab1.template",  dest: "/root/scripts/jinja2_lab1.template", mode: "0644"}
    - {src: "netconf_lab1.py",  dest: "/root/scripts/netconf_lab1.py", mode: "0755"}
    - {src: "netconf_lab2.py",  dest: "/root/scripts/netconf_lab2.py", mode: "0755"}
    - {src: "netconf_lab3.py",  dest: "/root/scripts/netconf_lab3.py", mode: "0755"}
    - {src: "restconf_lab1.py",  dest: "/root/scripts/restconf_lab1.py", mode: "0755"}
    - {src: "nativeapi_lab1.py",  dest: "/root/scripts/nativeapi_lab1.py", mode: "0755"}
    - {src: "nativeapi_lab2.py",  dest: "/root/scripts/nativeapi_lab2.py", mode: "0755"}
    - {src: "nativeapi_lab3.py",  dest: "/root/scripts/nativeapi_lab3.py", mode: "0755"}
    - {src: "nativeapi_lab4.py",  dest: "/root/scripts/nativeapi_lab4.py", mode: "0755"}
    - {src: "nativeapi_lab5.py",  dest: "/root/scripts/nativeapi_lab5.py", mode: "0755"}
    - {src: "sdk_lab1.py",  dest: "/root/scripts/sdk_lab1.py", mode: "0755"}
    - {src: "sdk_lab2.py",  dest: "/root/scripts/sdk_lab2.py", mode: "0755"}
    - {src: "files/Cisco/ASA/asa-restapi-132200-lfbff-k8.SPA",  dest: "/opt/customtftp/tftproot/asa-restapi-132200-lfbff-k8.SPA", mode: "0644"}
    - {src: "files/Cisco/CUCM/cucm-data-dictionary-12-0.zip",  dest: "/opt/unetlab/html/files/cucm-data-dictionary-12-0.zip", mode: "0644"}
    - {src: "files/Cisco/CUCM/axlsqltoolkit.zip",  dest: "/usr/src/axlsqltoolkit/axlsqltoolkit.zip", mode: "0644"}
  notify: reload_dhcpd

- name: "CONFIGURING THE FIREWALL"
  copy:
    src: "rules.v4"
    dest: "/etc/iptables/rules.v4"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload_iptables

- name: "CONFIGURING THE ROUTER"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^[#]?net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
  notify: reload_sysctl

- name: "START SERVICES AT BOOT"
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
    masked: no
  with_items:
    - isc-dhcp-server.service

- name: "DISABLE SERVICES"
  systemd:
    name: "{{item}}"
    state: stopped
    enabled: no
    masked: yes
  with_items:
    - isc-dhcp-server6.service

- name: "CLONING GIT REPOSITORIES"
  git:
    repo: "{{item.repo}}"
    dest: "/usr/src/{{item.dest}}"
    force: yes
  with_items:
    - {repo: "https://github.com/CiscoSE/Cisco-POAP", dest: "Cisco-POAP"}
    - {repo: "https://github.com/networktocode/ntc-templates", dest: "ntc-templates"}
    - {repo: "https://github.com/datacenter/acitoolkit", dest: "acitoolkit"}
