---
# Customizations (included by configuration.yaml)
sun.sun:
  friendly_name: Giorno/Notte

sensor.moon:
  friendly_name: Luna

sensor.today_forecasts_symbol:
  friendly_name: Meteo (oggi)

sensor.today_forecasts_temperature:
  friendly_name: Temperature (oggi)

sensor.today_forecasts_humidity:
  friendly_name: Umidità (oggi)
  icon: mdi:water

sensor.today_forecasts_fog:
  friendly_name: Nebbia (oggi)
  icon: mdi:format-align-justify

# iOS
{% for device_name, device in hass.ios.items() %}
device_tracker.{{device_name}}:
  friendly_name: {{device.friendly_name}}

device_tracker.{{device_name}}_battery_level:
  friendly_name: Batteria ({{device.friendly_name}})
{% endfor %}

# Zones
{% for zone in hass.zones %}
zone.{{zone.name}}:
  friendly_name: {{zone.friendly_name}}
{% endfor %}
