---
# Groups (included by configuration.yaml)

# Views
default_view:
  view: yes
  name: Home
  icon: mdi:home
  entities:
{% for device_name, device in hass.ios.items() %}
    - device_tracker.{{device_name}}
{% endfor %}
    - group.environment
    - group.phones
    - group.wifi
    - group.lan


# security:
#   view: yes
#   name: Sicurezza
#   entities:
#
# ground_floor:
#   view: yes
#   name: Piano Terra
#   entities:
#
# first_floor:
#   view: yes
#   name: Primo Piano
#   entities:
#
# outdoor:
#   view: yes
#   name: Esterno
#   entities:

# Groups
{% for group_name, group in hass.groups.items() %}
{{group_name}}:
  view: no
  name: {{group.friendly_name}}
  control: hidden
  entities:
{% for device in group.entities: %}
    - {{device}}
{% endfor %}
{% endfor %}

environment:
  view: no
  name: Informazioni
  control: hidden
  entities:
    - sun.sun
    - sensor.moon
    - sensor.today_forecasts_symbol
    - sensor.today_forecasts_temperature
    - sensor.today_forecasts_humidity
    - sensor.today_forecasts_windSpeed
    - sensor.today_forecasts_fog

phones:
  view: no
  name: Telefoni
  control: hidden
  entities:
{% for phone_name, phone in hass.ios.items() %}
    - sensor.{{phone_name}}_battery_level
    - sensor.{{phone_name}}_battery_state
{% endfor %}

# environment:
#   view: no
#   name: Informazioni
#   control: hidden
#   entities:
#     - sensor.date
#     - sensor.time
#     - sun.sun
#     - sensor.moon
#     - sensor.yr_symbol

# weather:
#   view: no
#   name: Meteo
#   control: hidden
#   entities:
#     - sensor.yr
