#!/usr/bin/env ansible-playbook
---
- hosts: pi_gateway
  gather_facts: False
  roles:
    - role: raspbian
      tags: raspbian
    - role: debian
      tags: debian
    - role: customization
      tags: customization
    - role: gateway
      tags: gateway
    - role: netdata
      tags: netdata
    - role: webserver
      tags: webserver
    #- role: nextcloud how is it upgraded??? https://pimylifeup.com/raspberry-pi-nextcloud-server/
    #  tags: nextcloud
    #- role: rocketchat
    #  tags: rocketchat
    - role: hass
      tags: hass

  pre_tasks:
    - name: "pre_task : VERIFYING ANSIBLE VERSION"
      delegate_to: localhost
      assert:
        that: "ansible_version.full is version_compare('2.6.0', '>=')"
        msg: "This playbook has been tested with Ansible >= 2.6.0, please upgrade."

    - name: "pre_task : TESTING REACHABILITY"
      wait_for:
        port: 22
        host: "{{ansible_host}}"
        timeout: 3
      connection: local

    - name: "pre_task : LOAD VARIABLES"
      include_vars: secrets-gateway.yaml
      tags: always
