---
- name: "UPGRADING (SAFE UPGRADE)"
  apt:
    upgrade: yes
    cache_valid_time: 86400
    force_apt_get: yes
    autoremove: yes

- name: "INSTALLING AND UPGRADING PACKAGES"
  apt:
    name: "{{item}}"
    update_cache: no
    force_apt_get: yes
    state: latest
  with_items:
    - apt-file
    - apt-transport-https
    - git
    - ntp
    - ntpdate
    - python-pip
    - python3-pip
    - vim

- name: "APPLYING TEMPLATES AND UPLOADING FILES"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "hostname", dest: "/etc/hostname", owner: "root", group: "root", mode: "0644"}
    - {src: "hosts", dest: "/etc/hosts", owner: "root", group: "root", mode: "0644"}

- name: "ENABLING SERVICES ON BOOT"
  systemd:
    name: "{{item.name}}"
    enabled: yes
    masked: no
    state: started
  with_items:
    - {name: "ssh.service"}
    - {name: "ntp.service"}

- register: hostname_current
  shell: "hostname"
  changed_when: false
- set_fact: hostname_new="{{inventory_hostname.split('.')[0] | lower}}"
- name: "REBOOTING"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: hostname_current.stdout_lines.0 != hostname_new
- wait_for_connection:
    connect_timeout: 20
    sleep: 15
    delay: 5
    timeout: 300
  when: hostname_current.stdout_lines.0 != hostname_new
