---
- name: "UPGRADING (SAFE UPGRADE)"
  apt:
    upgrade: yes
    cache_valid_time: 86400
    force_apt_get: yes
    autoremove: yes
  async: 1800
  poll: 15

- name: "REMOVING UNWANTED PACKAGES"
  apt:
    name: "{{item}}"
    update_cache: no
    force_apt_get: yes
    state: absent
    purge: yes
  with_items:
    - avahi-daemon
    - bluez
    - bluez-firmware
    - nfs-common
  async: 1800
  poll: 15

- name: "INSTALLING AND UPGRADING PACKAGES"
  apt:
    name: "{{item}}"
    update_cache: no
    force_apt_get: yes
    state: latest
  with_items:
    - apt-file
    - apt-transport-https
    - cpufrequtils
    - ntp
    - ntpdate
    - python-pip
    - python3-pip
    - ruby
    - unattended-upgrades
  async: 1800
  poll: 15

- name: "APPLYING TEMPLATES AND UPLOADING FILES"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "hostname", dest: "/etc/hostname", owner: "root", group: "root", mode: "0644"}
    - {src: "hosts", dest: "/etc/hosts", owner: "root", group: "root", mode: "0644"}

- name: "CONFIGURING TIMEZONE"
  file:
    src: "/usr/share/zoneinfo/{{timezone}}"
    dest: /etc/localtime
    state: link
  register: cfg_timezone
- command: dpkg-reconfigure -f noninteractive tzdata
  when: cfg_timezone.changed == True

- name: "CONFIGURING UNATTENDED UPDGRADE"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "unattended-upgrades", dest: "/etc/apt/apt.conf.d/50unattended-upgrades", owner: "root", group: "root", mode: "0644"}
  register: cfg_unattendedupg
- systemd:
    name: "unattended-upgrades.service"
    state: restarted
  when: cfg_unattendedupg.changed == True

- name: "ENABLING SERVICES ON BOOT"
  systemd:
    name: "{{item.name}}"
    enabled: yes
    masked: no
    state: started
  with_items:
    - {name: "ssh.service"}
    - {name: "ntp.service"}
    - {name: "unattended-upgrades.service"}

- name: "CONFIGURING CPUFREQUTILS"
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "cpufrequtils", dest: "/etc/default/cpufrequtils", owner: "root", group: "root", mode: "0644"}
  register: cfg_cpufrequtils
- systemd:
    name: "cpufrequtils.service"
    enabled: yes
    masked: no
- systemd:
    name: "cpufrequtils.service"
    state: restarted
  when: cfg_cpufrequtils.changed == True

- register: hostname_current
  shell: "hostname"
  changed_when: false
- set_fact: hostname_new="{{inventory_hostname.split('.')[0] | lower}}"
- name: "REBOOTING"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: hostname_current.stdout_lines.0 != hostname_new
- wait_for_connection:
    connect_timeout: 20
    sleep: 15
    delay: 5
    timeout: 300
  when: hostname_current.stdout_lines.0 != hostname_new
