---
# Entering and Exiting Zones (included by configuration.yaml)
{% for zone in hass.zones %}
{% for device_name, device in hass.ios.items() %}
- alias: {{device_name}}_entering_{{zone.name}}
  trigger:
    - platform: zone
      entity_id: device_tracker.{{device_name}}
      zone: zone.{{zone.name}}
      event: enter
  action:
    service: notify.all_but_{{device_name}}
    data:
      title: {{device.friendly_name}}
      message: {{device.friendly_name}} is at {{zone.friendly_name}}

- alias: {{device_name}}_leaving_{{zone.name}}
  trigger:
    - platform: zone
      entity_id: device_tracker.{{device_name}}
      zone: zone.{{zone.name}}
      event: leave
  action:
    service: notify.all_but_{{device_name}}
    data:
      title: {{device.friendly_name}}
      message: {{device.friendly_name}} left {{zone.friendly_name}}
{% endfor %}
{% endfor %}
