---
# tasks file for gateway
- name: "INSTALLING AND UPGRADING PACKAGES"
  apt:
    name: "{{item}}"
    update_cache: no
    force_apt_get: yes
    state: latest
  with_items:
    - ddclient
    - dnsmasq
    - dnsutils
    - iptables
    - iptables-persistent
    - pppoeconf
    - tcpdump
    - wide-dhcpv6-client

- name: "CONFIGURING THE FIREWALL"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "rules.v4", dest: "/etc/iptables/rules.v4", owner: "root", group: "root", mode: "0640"}
    - {src: "rules.v6", dest: "/etc/iptables/rules.v6", owner: "root", group: "root", mode: "0640"}
  register: cfg_templates
- shell: "{{item.cmd}}"
  with_items:
    - {cmd: "iptables-restore < /etc/iptables/rules.v4"}
    - {cmd: "ip6tables-restore < /etc/iptables/rules.v6"}
  changed_when: cfg_templates.changed == True

- name: "CONFIGURING SYSTEM OPTIONS"
  lineinfile:
    dest: "{{item.dest}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {dest: "/etc/sysctl.conf", regexp: "^[#]?net.ipv4.ip_forward", line: "net.ipv4.ip_forward=1"}
    - {dest: "/etc/sysctl.conf", regexp: "^[#]?net.ipv6.conf.all.forwarding", line: "net.ipv6.conf.all.forwarding=1"}
  register: cfg_options

- name: "CONFIGURING DNSMASQ"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "dnsmasq.conf", dest: "/etc/dnsmasq.conf", owner: "root", group: "root", mode: "0644"}
  register: cfg_dnsmasq
- systemd:
    name: dnsmasq.service
    state: restarted
  when: cfg_dnsmasq.changed == True
- systemd:
    name: dnsmasq.service
    enabled: yes
    masked: no
    state: started

- name: "CONFIGURING NETWORKS"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "eth0-cfg", dest: "/etc/network/interfaces.d/eth0-cfg", owner: "root", group: "root", mode: "0644"}
    - {src: "eth1-cfg", dest: "/etc/network/interfaces.d/eth1-cfg", owner: "root", group: "root", mode: "0644"}
    - {src: "ppp0-cfg", dest: "/etc/network/interfaces.d/ppp0-cfg", owner: "root", group: "root", mode: "0644"}
  register: cfg_networks
- systemd:
    name: dhcpcd.service
    enabled: False
    state: stopped

- name: "CONFIGURING DDCLIENT"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "ddclient.conf", dest: "/etc/ddclient.conf", owner: "root", group: "root", mode: "0600"}
  register: cfg_ddclient
- systemd:
    name: ddclient.service
    state: restarted
  when: cfg_ddclient.changed == True
- systemd:
    name: ddclient.service
    enabled: yes
    masked: no
    state: started

- name: "IPV6 (VIA PPPOE FOR TIM BROADBAND)"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "dhcp6c.conf", dest: "/etc/wide-dhcpv6/dhcp6c.conf", owner: "root", group: "root", mode: "0644"}
    - {src: "ppp0-cfg", dest: "/etc/network/interfaces.d/ppp0-cfg", owner: "root", group: "root", mode: "0644"}
    - {src: "telecom-ipv6", dest: "/etc/ppp/peers/telecom-ipv6", owner: "root", group: "root", mode: "0640"}
    - {src: "ipv6-up-internal_network", dest: "/etc/ppp/ipv6-up.d/internal_network", owner: "root", group: "root", mode: "0755"}
    - {src: "ipv6-down-internal_network", dest: "/etc/ppp/ipv6-down.d/internal_network", owner: "root", group: "root", mode: "0755"}
    - {src: "dnsmasq-ipv6.template", dest: "/etc/dnsmasq-ipv6.template", owner: "root", group: "root", mode: "0644"}
  register: cfg_ipv6_1
- lineinfile:
    dest: "{{item.dest}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {dest: "/etc/default/wide-dhcpv6-client", regexp: "^INTERFACES", line: 'INTERFACES="ppp0"'}
  register: cfg_ipv6_2
- systemd:
    name: wide-dhcpv6-client.service
    enabled: no
    masked: no

- name: "REBOOTING"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cfg_networks.changed == True
- wait_for_connection:
    connect_timeout: 20
    sleep: 15
    delay: 5
    timeout: 300
  when: cfg_networks.changed == True
