---
- platform: command_line
  name: printer0_toner
  command: "echo $(snmpget -v2c -Oqv -c 932d86fs8j329d3k printer0.cydonia.local 1.3.6.1.2.1.43.11.1.1.9.1.1)/$(snmpget -v2c -Oqv -c {{snmp_community}} printer0.cydonia.local 1.3.6.1.2.1.43.11.1.1.8.1.1) | bc -l"
  unit_of_measurement: "%"
  value_template: '{% raw %}{{ value | multiply(100) | round(0) }}{% endraw %}'
- platform: command_line
  name: printer0_alert
  command: "snmpget -v2c -Oqv -c {{snmp_community}} printer0.cydonia.local 1.3.6.1.2.1.43.18.1.1.8"
  #value_template: '{% raw %}{% if value == "occupied" -%}on{%- else -%}off{%- endif %}{% endraw %}'
