#!/usr/bin/env ansible-playbook
---
- hosts: eve_hosts
  gather_facts: False
  vars:
    hash: $6$antvLjR5$uLu5V.2TFwv9v8gCOfJvZBjWiZMOHReeYwZs5tL2IpY6MgY0m2OlTLYaLIKZ.zCsQJDWt7fb476G5vq9KSWcn0
  roles:
    - role: first_connection
      tags: first_connection
    - role: prerequisites
      tags: prerequisites
    - role: eveng
      tags: eveng
    - role: gitlab
      tags: gitlab

  pre_tasks:
    - name: "pre_task : VERIFYING ANSIBLE VERSION"
      delegate_to: localhost
      assert:
        that: "ansible_version.full is version_compare('2.6.0', '>=')"
        msg: "This playbook has been tested with Ansible >= 2.6.0, please upgrade."

    - name: "pre_task : TESTING REACHABILITY"
      wait_for:
        port: 22
        host: "{{ansible_host}}"
        timeout: 3
      connection: local
