---
- hosts: all
  tasks:
    - stat: path=/etc/apt/sources.list.d/gitlab_gitlab-ee.list
      register: gitlab_repo
    - name: GETTING GITLAB INSTALLATION SCRIPT
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: 0755
    - name: INSTALLING GITLAB REPOSITORY
      shell: "/tmp/script.deb.sh"
      changed_when: false
      when: gitlab_repo.stat.exists == False
    - name: INSTALLING GITLAB
      apt:
        name: gitlab-ee
        update_cache: yes
        force_apt_get: yes
      environment:
        EXTERNAL_URL: http://eve-ng.example.com:9080
# https://docs.gitlab.com/omnibus/settings/database.html#seed-the-database-fresh-installs-only
# install also git

# install runners
# https://docs.gitlab.com/runner/install/linux-manually.html

# after a reboot
#  gitlab-runner status
# disable or stom tomcat8
# systemctl stop tomcat8
# restart gitlab (unicorn)
